### ISSUE TITLE
Step user-registration fail

### ISSUE THREAD

**Issue by orangeagain** [immutable/imx-examples#16]
After set "OWNER_ACCOUNT_PRIVATE_KEY" and run "npm run onboarding:user-registration"
report those error:
```
> @imtbl/imx-sdk-example@1.0.0 onboarding:user-registration   
> ts-node -r tsconfig-paths/register -r dotenv/config ./src/onboarding/1-user-registration.ts

INFO 2022-04-11T01:13:25+08:00 Registering user... | component=[IMX-USER-REGISTRATION] extra=undefined
ERROR 2022-04-11T01:13:26+08:00 {} | component=[IMX-USER-REGISTRATION] extra=undefined
Error: {}
    at R:\html\imx-examples-main\imx-examples-main\src\onboarding\1-user-registration.ts:40:13
    at step (R:\html\imx-examples-main\imx-examples-main\src\onboarding\1-user-registration.ts:44:23)
    at Object.throw (R:\html\imx-examples-main\imx-examples-main\src\onboarding\1-user-registration.ts:25:53)
    at rejected (R:\html\imx-examples-main\imx-examples-main\src\onboarding\1-user-registration.ts:17:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
help me ,please

**Comment by orangeagain** [comment]
```
found more deep log:
INFO 2022-04-11T01:24:29+08:00 Registering user... | component=[IMX-USER-REGISTRATION] extra=undefined
ERROR 2022-04-11T01:24:35+08:00 Errno: -4077 Errcode: ECONNRESET | component=[IMX-USER-REGISTRATION] extra=undefined
Error: Errno: -4077 Errcode: ECONNRESET
    at f (R:\html\imx-examples-main\imx-examples-main\node_modules\@imtbl\imx-sdk\src\libs\utils.ts:32:12)
    at R:\html\imx-examples-main\imx-examples-main\node_modules\@imtbl\imx-sdk\node_modules\fp-ts\es6\Either.js:419:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
might be china network problem?
